version: '3.9'
services:
  ms-calculos:
    image: devbino/ms-calculos:latest
    restart: always
    build: ./api-rest
    working_dir: /api-rest
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://${MYSQL_ROOT_HOST}:3306/${MYSQL_DATABASE}
      SPRING.DATASOURCE.USERNAME: ${MYSQL_USER}
      SPRING.DATASOURCE.PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - 3000:3000
    command: mvn spring-boot:run

    networks:
      - calculos-microsservices

  ms-calculos-processor:
    image: devbino/ms-calculos-processor:latest
    restart: always
    build: ./calculo-processor
    working_dir: /calculo-processor
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://${MYSQL_ROOT_HOST}:3306/${MYSQL_DATABASE}
      SPRING.DATASOURCE.USERNAME: ${MYSQL_USER}
      SPRING.DATASOURCE.PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - 8090:8090
    command: mvn spring-boot:run

    networks:
      - calculos-microsservices

networks:
  calculos-microsservices:
    driver: bridge