name: Deploy Microsserviços Calculos

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setupe Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Acessando sub projeto Api-Rest e Fazendo Build
              run: cd api-rest && mvn clean install -DskipTests

            - name: Acessando sub projeto Calculo-Processor e Gerando Build
              run: cd calculo-processor && mvn clean install -DskipTests

            - name: Remover Jar Files
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                script: |
                     rm ../sistema/calculos-0.0.1-SNAPSHOT.jar || true
                     rm ../sistema/processor-0.0.1-SNAPSHOT.jar || true

            - name: Enviando JARs para a VPS
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                local_file: |
                     api-rest/target/calculos-0.0.1-SNAPSHOT.jar
                     calculo-processor/target/processor-0.0.1-SNAPSHOT.jar
                remote_path: "../sistema/"
                