name: Deploy Microsserviços Calculos

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setupe Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Acessando sub projeto Api-Rest e Fazendo Build
              run: cd api-rest && mvn clean install -DskipTests

            - name: Acessando sub projeto Calculo-Processor e Gerando Build
              run: cd ../calculo-processor/ && mvn clean install -DskipTests
            
            - name: Retornando para Raiz
              run: cd .. && ls
              
