name: Deploy Microsserviços - Calculos

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setupe Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Acessando Projeto Api-Rest e Gerando Build
              run: cd api-rest && mvn clean install -DskipTests

            - name: Acessando Projeto Calculo-Processor e Gerando Build
              run: cd calculo-processor && mvn clean install -DskipTests

            - name: Remover JARs antigos da VPS
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                key: ${{ secrets.VPS_SSH_KEY }}
                port: 22
                script: |
                  rm -f /sistema/*.jar

            - name: Deploy JARs to VPS
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                key: ${{ secrets.VPS_SSH_KEY }}
                port: 22
                source: "api-rest/target/calculos-0.0.1-SNAPSHOT.jar,calculo-processor/target/processor-0.0.1-SNAPSHOT.jar"
                target: "/sistema/"
                