name: Deploy Microsserviços Calculos

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3