name: Deploy Microsserviços Calculos

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setupe Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Build Project
              run: mvn clean install -DskipTests
            - name: Exibindo diretorios
              run: ls la
